#Main
sl_core_main:
    resource: "@SLCoreBundle/Resources/config/routing/main.yml"
    prefix: /

#Server
sl_core_server:
    resource: "@SLCoreBundle/Resources/config/routing/server.yml"
    prefix: /back_end/server

#Object
sl_core_object:
    resource: "@SLCoreBundle/Resources/config/routing/object.yml"
    prefix: /back_end/object

#Property
sl_core_property:
    resource: "@SLCoreBundle/Resources/config/routing/property.yml"
    prefix: /back_end/object/property

#ChoiceList
sl_core_choice_list:
    resource: "@SLCoreBundle/Resources/config/routing/choiceList.yml"
    prefix: /back_end/choice_list

#ChoiceItem
sl_core_choice_item:
    resource: "@SLCoreBundle/Resources/config/routing/choiceItem.yml"
    prefix: /back_end/choice_item

#Front
sl_core_font:
    resource: "@SLCoreBundle/Resources/config/routing/front.yml"
    prefix: /front_end

#Search
sl_core_search:
    resource: "@SLCoreBundle/Resources/config/routing/search.yml"
    prefix: /front_end/search

#Authentification
# login:
#     pattern:   /login
#     defaults:  { _controller: SLCoreBundle:Default:login }

# login_check:
#     pattern:   /login_check

