#Main
sl_core_main:
    resource: "@SLCoreBundle/Resources/config/routing/main.yml"
    prefix: /

#Server
sl_core_server:
    resource: "@SLCoreBundle/Resources/config/routing/server.yml"
    prefix: /back_end/server

#EntityClass
sl_core_entity_class:
    resource: "@SLCoreBundle/Resources/config/routing/entity_class/entity_class.yml"
    prefix: /back_end/entity_class

#Property
sl_core_property:
    resource: "@SLCoreBundle/Resources/config/routing/entity_class/property.yml"
    prefix: /back_end/entity_class/property

#ChoiceList
sl_core_choice_list:
    resource: "@SLCoreBundle/Resources/config/routing/choice/choiceList.yml"
    prefix: /back_end/choice_list

#ChoiceItem
sl_core_choice_item:
    resource: "@SLCoreBundle/Resources/config/routing/choice/choiceItem.yml"
    prefix: /back_end/choice_item

#Front
sl_core_font:
    resource: "@SLCoreBundle/Resources/config/routing/front.yml"
    prefix: /front_end

#Search
sl_core_search:
    resource: "@SLCoreBundle/Resources/config/routing/search.yml"
    prefix: /front_end/search


