parameters:
    sl_core.bundle: SL/CoreBundle
    sl_data.bundle: SL/DataBundle
    symfony.config_path : %kernel.root_dir%/config/

services:
    sl_core.doctrine:
        class: SL\CoreBundle\Services\DoctrineService
        arguments: [@filesystem, @doctrine, @kernel, %sl_core.bundle%,%sl_data.bundle%]

    sl_core.js_tree:
        class: SL\CoreBundle\Services\JSTreeService
        arguments: [@router, @translator, @sl_core.icon]

    sl_core.icon:
        class: SL\CoreBundle\Services\IconService

    sl_core.object:
        class: SL\CoreBundle\Services\ObjectService
        arguments: [@doctrine, @translator, @form.factory, @router]

    sl_core.property:
        class: SL\CoreBundle\Services\PropertyService
        arguments: [@doctrine.orm.entity_manager, @translator, @form.factory, @router]

    sl_core.data_list:
        class: SL\CoreBundle\Services\DataListService
        arguments: [@doctrine.orm.entity_manager, @translator, @form.factory, @router]

    sl_core.data_list_value:
        class: SL\CoreBundle\Services\DataListValueService
        arguments: [@form.factory, @router]

    sl_core.front:
        class: SL\CoreBundle\Services\FrontService
        arguments: [@form.factory, @router, @doctrine.orm.entity_manager, @sl_core.object, @sl_core.doctrine, @translator]

    sl_core.elastica:
        class: SL\CoreBundle\Services\ElasticaService
        arguments: [@doctrine.orm.entity_manager, @router, @sl_core.js_tree, %sl_data.bundle%, %symfony.config_path%]

    sl_core.search:
        class: SL\CoreBundle\Services\SearchService
        arguments: [@form.factory, @router]

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    #Doctrine Listener
    sl_core.listener:
        class: SL\CoreBundle\Listener\DoctrineListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    #Form Service
    sl_core.form.type.data.list:
        class: SL\CoreBundle\Form\DataListType
        tags:
            - { name: form.type, alias: data_list }

    sl_core.form.type.data.list.value:
        class: SL\CoreBundle\Form\DataListValueType
        tags:
            - { name: form.type, alias: data_list_value }

    sl_core.form.type.object:
        class: SL\CoreBundle\Form\ObjectType
        tags:
            - { name: form.type, alias: object }

    sl_core.form.type.document:
        class: SL\CoreBundle\Form\DocumentType
        tags:
            - { name: form.type, alias: document }

    sl_core.form.type.object.calculated.name:
        class: SL\CoreBundle\Form\ObjectCalculatedNameType
        tags:
            - { name: form.type, alias: object_calculated_name }

    sl_core.form.type.property.choice:
        class: SL\CoreBundle\Form\PropertyChoiceType
        tags:
            - { name: form.type, alias: property_choice }

    sl_core.form.type.property:
        class: SL\CoreBundle\Form\PropertyType
        tags:
            - { name: form.type, alias: property }

    sl_core.form.type.entity.property:
        class: SL\CoreBundle\Form\EntityPropertyType
        tags:
            - { name: form.type, alias: entity_property }

    sl_core.form.type.choice.property:
        class: SL\CoreBundle\Form\ListPropertyType
        tags:
            - { name: form.type, alias: choice_property }
    
    sl_core.form.type.search:
        class: SL\CoreBundle\Form\SearchType
        tags:
            - { name: form.type, alias: sl_core_search }

    #Custom form validator service
    validator.unique.calculated_name_pattern:
        class: SL\CoreBundle\Validator\Constraints\CalculatedNamePatternValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: calculated_name_pattern }

