parameters:
    sl_data.bundle: SL/DataBundle
    symfony.config_path : %kernel.root_dir%/config/
    sl_core.number_of_versions : 5
    sl_core.number_of_search_results : 50
    sl_core.date_format : 'd/m/Y'

services:
    sl_core.doctrine:
        class: SL\CoreBundle\Services\DoctrineService
        arguments: [@filesystem, @doctrine, @kernel, %sl_data.bundle%, %sl_core.number_of_versions%]

    sl_core.js_tree:
        class: SL\CoreBundle\Services\JSTreeService
        arguments: [@router, @sl_core.icon]

    sl_core.icon:
        class: SL\CoreBundle\Services\IconService

    sl_core.entity_class:
        class: SL\CoreBundle\Services\EntityClass\EntityClassService
        arguments: [@doctrine, @translator, @form.factory, @router]

    sl_core.property:
        class: SL\CoreBundle\Services\EntityClass\PropertyService
        arguments: [@doctrine.orm.entity_manager, @translator, @form.factory, @router]

    sl_core.choice_list:
        class: SL\CoreBundle\Services\Choice\ChoiceListService
        arguments: [@doctrine.orm.entity_manager, @translator, @form.factory, @router]

    sl_core.choice_item:
        class: SL\CoreBundle\Services\Choice\ChoiceItemService
        arguments: [@form.factory, @router]

    sl_core.entity:
        class: SL\CoreBundle\Services\EntityService
        arguments: [@form.factory, @router, @doctrine, %sl_core.number_of_versions%, %sl_core.date_format%]

    sl_core.elastica:
        class: SL\CoreBundle\Services\ElasticaService
        arguments: [@doctrine.orm.entity_manager, @router, @sl_core.js_tree, %sl_data.bundle%, %symfony.config_path%]

    sl_core.test:
        class: SL\CoreBundle\Services\TestService

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    #Doctrine Listener
    sl_core.listener:
        class: SL\CoreBundle\Listener\DoctrineListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }

    #Form Service
    sl_core.form.type.choice.list:
        class: SL\CoreBundle\Form\Choice\ChoiceListType
        tags:
            - { name: form.type, alias: sl_core_choice_list }

    sl_core.form.type.choice.item:
        class: SL\CoreBundle\Form\Choice\ChoiceItemType
        tags:
            - { name: form.type, alias: sl_core_choice_item }

    sl_core.form.type.entity.class:
        class: SL\CoreBundle\Form\EntityClass\EntityClassType
        tags:
            - { name: form.type, alias: sl_core_entity_class }

    sl_core.form.type.entity.class.calculated.name:
        class: SL\CoreBundle\Form\EntityClass\EntityClassCalculatedNameType
        tags:
            - { name: form.type, alias: sl_core_entity_class_calculated_name }

    sl_core.form.type.property.select:
        class: SL\CoreBundle\Form\EntityClass\PropertySelectType
        tags:
            - { name: form.type, alias: sl_core_property_select }

    sl_core.form.type.property:
        class: SL\CoreBundle\Form\EntityClass\PropertyType
        tags:
            - { name: form.type, alias: sl_core_property }

    sl_core.form.type.property.entity:
        class: SL\CoreBundle\Form\EntityClass\PropertyEntityType
        tags:
            - { name: form.type, alias: sl_core_property_entity }

    sl_core.form.type.property.choice:
        class: SL\CoreBundle\Form\EntityClass\PropertyChoiceType
        tags:
            - { name: form.type, alias: sl_core_property_choice }
    
    sl_core.form.type.search:
        class: SL\CoreBundle\Form\SearchType
        tags:
            - { name: form.type, alias: sl_core_search }

    sl_core.form.type.entity:
        class: SL\CoreBundle\Form\EntityType
        arguments: [@doctrine.orm.entity_manager, @sl_core.entity_class, @translator]
        tags:
            - { name: form.type, alias: sl_core_entity }

    sl_core.form.type.entity.version:
        class: SL\CoreBundle\Form\EntityVersionType
        tags:
            - { name: form.type, alias: sl_core_entity_version }

    #Custom form validator service
    validator.unique.calculated_name_pattern:
        class: SL\CoreBundle\Validator\Constraints\CalculatedNamePatternValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: calculated_name_pattern }

    #ParamConverter
    sl_core.paramconverter.entity_class:
        class: SL\CoreBundle\ParamConverter\EntityClassParamConverter
        arguments: ["SL\CoreBundle\Entity\EntityClass\EntityClass", @doctrine.orm.entity_manager]
        tags:
            - { name: request.param_converter, priority: 20 }

    sl_core.paramconverter.entity:
        class: SL\CoreBundle\ParamConverter\EntityParamConverter
        arguments: ["SL\MasterBundle\Entity\AbstractEntity", @doctrine]
        tags:
            - { name: request.param_converter, priority: 21 }