imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
#    - { resource: elastica.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        app_version: v%application_version%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ SLCoreBundle]
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
    assets:
        jquery_js:
            inputs:
               - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
            filters:
               - ?yui_js
            output: assets/js/jquery.min.js
        jquery_ui_css:
            inputs:
               - %kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/jquery-ui.min.css
            filters:
               - ?yui_css
            output: assets/js/jquery-ui.min.css
        jquery_ui_js:
            inputs:
               - %kernel.root_dir%/../vendor/components/jqueryui/jquery-ui.min.js
            filters:
               - ?yui_js
            output: assets/js/jquery-ui.min.js
        bootstrap_css:
            inputs:
               - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css
            filters:
               - ?yui_css
            output: assets/css/bootstrap.min.css
        bootstrap_theme_css:
            inputs:
               - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.min.css
            filters:
               - ?yui_css
            output: assets/css/bootstrap-theme.min.css
        bootstrap_js:
            inputs:
               - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
            filters:
               - ?yui_js
            output: assets/js/bootstrap.min.js
        fontawesome_css:
            inputs:
               - %kernel.root_dir%/../vendor/fortawesome/font-awesome/css/font-awesome.min.css
            filters:
               - ?yui_css
            output: assets/css/font-awesome.min.css
        mopabootstrap_collection_js:
            inputs:
               - %kernel.root_dir%/../web/bundles/mopabootstrap/js/mopabootstrap-collection.js
            filters:
               - ?yui_js
            output: assets/js/mopabootstrap-collection.js
        bootstrap_modal_css:
            inputs:
               - %kernel.root_dir%/../vendor/jschr/bootstrap-modal/css/*
            filters:
               - ?yui_css
            output: assets/css/bootstrap-modal.css
        bootstrap_modal_js:
            inputs:
               - %kernel.root_dir%/../vendor/jschr/bootstrap-modal/js/*
            filters:
               - ?yui_js
            output: assets/js/bootstrap-modal.js
        bootstrap_iconpicker_js:
            inputs:
               - %kernel.root_dir%/../web/bundles/slcore/js/bootstrap-iconpicker.min.js
            filters:
               - ?yui_js
            output: assets/js/bootstrap_iconpicker.min.js
        bootstrap_icon_picker_css:
            inputs:
               - %kernel.root_dir%/../web/bundles/slcore/css/bootstrap-iconpicker.min.css
            filters:
               - ?yui_css
            output: assets/css/bootstrap-iconpicker.min.css
        bootstrap_icon_picker_js:
            inputs:
               - %kernel.root_dir%/../web/bundles/slcore/js/bootstrap-iconpicker.min.js
            filters:
               - ?yui_js
            output: assets/js/bootstrap-iconpicker.min.js
        js_tree_css:
            inputs:
               - %kernel.root_dir%/../vendor/vakata/jstree/dist/themes/default/style.min.css
            filters:
               - ?yui_css
            output: assets/css/style.min.css
        js_tree_js:
            inputs:
               - %kernel.root_dir%/../vendor/vakata/jstree/dist/jstree.min.js
            filters:
               - ?yui_js
            output: assets/js/jstree.min.js
        fos_js_routting_js:
            inputs:
               - %kernel.root_dir%/../web/bundles/fosjsrouting/js/router.js
            filters:
               - ?yui_js
            output: assets/js/fosjsrouting-router.js
        insert_at_caret_js:
            inputs:
               - %kernel.root_dir%/../web/bundles/slcore/js/insert-at-caret.js
            filters:
               - ?yui_js
            output: assets/js/insert-at-caret.js
        custom_css:
            inputs:
               - %kernel.root_dir%/../web/bundles/slcore/css/custom.css
            filters:
               - ?yui_css
            output: assets/css/custom.css
        custom_js:
            inputs:
               - %kernel.root_dir%/../web/bundles/slcore/js/custom.js
            filters:
               - ?yui_js
            output: assets/js/custom.js

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   "%driver%"
                host:     "%host%"
                port:     "%port%"
                dbname:   "%name%"
                user:     "%user%"
                password: "%password%"
                charset:  UTF8
                # if using pdo_sqlite as your database driver, add the path in parameters.yml
                # e.g. database_path: "%kernel.root_dir%/data/data.db3"
                # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    SLCoreBundle: ~
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false


#Stof_doctrine_extension_bundle
stof_doctrine_extensions:
    default_locale: fr
    orm:
        default:
            loggable: false
            sortable: true
            softdeleteable: true
            tree: true
            timestampable: true
            uploadable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Mopabootstrap
mopa_bootstrap:
    menu: ~
    form:
        render_optional_text: false
        render_required_asterisk: true
    icons:
        # Icon set to use: ['glyphicons','fontawesome','fontawesome4']
        icon_set: fontawesome4

#Genmenu
genemu_form:
    select2: ~
    date:
        enabled: true
        configs: { changeMonth: true, changeYear: true, minDate: "-50Y", maxDate: "+50Y"}
    tinymce: ~

#JMSTranslation Configuration
jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%/Resources]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [cache, data, logs]
            extractors: []
        SLCoreBundle:
            dirs: [%kernel.root_dir%/../src/SL/CoreBundle]
            output_dir: %kernel.root_dir%/../src/SL/CoreBundle/Resources/translations
            ignored_domains: [routes]
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [cache, data, logs]
            extractors: []

#JMSDIExtra Configuration
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [SLCoreBundle]
        directories: ["%kernel.root_dir%/../src"]

#FOSElastica
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        slcore:
            types:
                EntityClass1:
                    mappings:
                        guid: ~
                        displayName: ~
                        document:
                            type: "object"
                            properties:
                                guid: ~
                                displayName: ~
                                encodedFile: 
                                    type : "attachment"
                    persistence:
                        driver: orm
                        model: SL\CoreBundle\Entity\Generated\EntityClass1
                        model_to_elastica_transformer:
                            service: sl_core.search.transformer.object_to_elastica_transformer
                        provider: ~
                        listener: ~
                        finder: ~
                EntityClass2:
                    mappings:
                        guid: ~
                        displayName: ~
                        document:
                            type: "object"
                            properties:
                                guid: ~
                                displayName: ~
                                encodedFile: 
                                    type : "attachment"
                    persistence:
                        driver: orm
                        model: SL\CoreBundle\Entity\Generated\EntityClass2
                        model_to_elastica_transformer:
                            service: sl_core.search.transformer.object_to_elastica_transformer
                        provider: ~
                        listener: ~
                        finder: ~


#Shiva versionning
shivas_versioning:
    version_parameter:    application_version