sl_master:
    resource: "@SLMasterBundle/Resources/config/routing.yml"
    prefix:   /

sl_data:
    resource: "@SLDataBundle/Resources/config/routing.yml"
    prefix:   /

sl_core:
    resource: "@SLCoreBundle/Resources/config/routing.yml"
    prefix:   /

#admin:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /admin

#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin

#sonata_user:
#    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
#    prefix: /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


JMSTranslationBundle_ui:
    resource: @JMSTranslationBundle/Controller/
    type:     annotation
    prefix:   /_trans