entity_class:
    pattern: /
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:index }
    requirements:
        _method: GET

entity_class_new:
    pattern: /new/{entity_class_id}
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:new, entity_class_id:0 }
    requirements:
        entity_class_id: \d+
        _method: GET 

entity_class_create:
    pattern: /create/{entity_class_id}
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:create }
    requirements:
        entity_class_id: \d+
        _method: POST 

entity_class_edit:
    pattern: /{entity_class_id}/edit
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:edit }
    requirements:
        entity_class_id: \d+
        _method: GET

entity_class_update:
    pattern: /{entity_class_id}/update
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:update }
    requirements:
        entity_class_id: \d+
        _method: PUT

entity_class_show:
    pattern: /{entity_class_id}/show
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:show }
    requirements:
        entity_class_id: \d+
        _method: GET 

entity_class_remove:
    pattern: /{entity_class_id}/remove
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:remove }
    requirements:
        entity_class_id: \d+
        _method: GET 

entity_class_delete:
    pattern: /{entity_class_id}/delete
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:delete }
    requirements:
        entity_class_id: \d+
        _method: DELETE

entity_class_update_icon:
    pattern: /{entity_class_id}/updateIcon
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:updateIcon }
    requirements:
        entity_class_id: \d+
        _method: PUT 

entity_class_edit_calculated_name:
    pattern: /{entity_class_id}/edit_calculated_name
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:editCalculatedName }
    requirements:
        entity_class_id: \d+
        _method: GET 

entity_class_update_calculated_name:
    pattern:  /{entity_class_id}/update_calculated_name
    defaults: { _controller: SLCoreBundle:EntityClass\EntityClass:updateCalculatedName }
    requirements:
        entity_class_id: \d+
        _method: PUT