property_new:
    pattern: /{entity_class_id}/new
    defaults: { _controller: SLCoreBundle:EntityClass\Property:new }
    requirements:
        entity_class_id: \d+
        _method: GET

property_select_form:
    pattern: /{entity_class_id}/select_form
    defaults: { _controller: SLCoreBundle:EntityClass\Property:selectForm }
    requirements:
        entity_class_id: \d+
        _method: GET

property_create:
    pattern: /{entity_class_id}/create/{formMode}
    defaults: { _controller: SLCoreBundle:EntityClass\Property:create }
    requirements: 
        entity_class_id: \d+
        _method: POST

property_edit:
    pattern: /{entity_class_id}.{id}/edit
    defaults: { _controller: SLCoreBundle:EntityClass\Property:edit }
    requirements:
        entity_class_id: \d+
        id: \d+
        _method: GET

property_update:
    pattern: /{entity_class_id}.{id}/update
    defaults: { _controller: SLCoreBundle:EntityClass\Property:update }
    requirements:
        entity_class_id: \d+
        id: \d+
        _method: PUT

property_remove:
    pattern: /{entity_class_id}.{id}/remove
    defaults: { _controller: SLCoreBundle:EntityClass\Property:remove }
    requirements:
        entity_class_id: \d+
        id: \d+
        _method: GET

property_delete:
    pattern:  /{entity_class_id}.{id}/delete
    defaults: { _controller: SLCoreBundle:EntityClass\Property:delete }
    requirements:
        entity_class_id: \d+
        id: \d+
        _method: DELETE

property_update_checkbox:
    pattern:  /{id}/updateCheckbox
    defaults: { _controller: SLCoreBundle:EntityClass\Property:updateCheckbox }
    requirements:
        id: \d+
        _method: PUT