choice_item_new:
    pattern: /{id}/new
    defaults: { _controller: SLCoreBundle:ChoiceItem:new }
    requirements:
        id: \d+

choice_item_create:
    pattern: /{id}/create
    defaults: { _controller: SLCoreBundle:ChoiceItem:create }
    requirements:
        id: \d+
        _method: POST 

choice_item_edit:
    pattern: /{id}/edit
    defaults: { _controller: SLCoreBundle:ChoiceItem:edit }
    requirements:
        id: \d+
        _method: GET 

choice_item_update:
    pattern: /{id}/update
    defaults: { _controller: SLCoreBundle:ChoiceItem:update }
    requirements:
        id: \d+
        _method: PUT

choice_item_remove:
    pattern:  /{id}/remove
    defaults: { _controller: SLCoreBundle:ChoiceItem:remove }
    requirements:
        id: \d+
        _method: GET 

choice_item_delete:
    pattern:  /{id}/delete
    defaults: { _controller: SLCoreBundle:ChoiceItem:delete }
    requirements:
        id: \d+
        _method: DELETE 

choice_item_update_icon:
    pattern:  /{id}/updateIcon
    defaults: { _controller: SLCoreBundle:ChoiceItem:updateIcon }
    requirements:
        id: \d+
        _method: PUT

choice_item_update_checkbox:
    pattern:  /{id}/updateCheckbox
    defaults: { _controller: SLCoreBundle:ChoiceItem:updateCheckbox }
    requirements:
        id: \d+
        _method: PUT