data_list:
    pattern: /
    defaults: { _controller: sl_core.data_list.controller:indexAction }

data_list_new:
    pattern: /new
    defaults: { _controller: sl_core.data_list.controller:newAction }

data_list_create:
    pattern: /create
    defaults: { _controller: sl_core.data_list.controller:createAction }
    requirements:
        _method: POST

data_list_edit:
    pattern: /{id}/edit
    defaults: { _controller: sl_core.data_list.controller:editAction }
    requirements:
        id: \d+

data_list_update:
    pattern: /{id}/update
    defaults: { _controller: sl_core.data_list.controller:updateAction }
    requirements:
        id: \d+
        _method: PUT

data_list_show:
    pattern: /{id}/show
    defaults: { _controller: sl_core.data_list.controller:showAction }
    requirements:
        id: \d+
    options:
        expose: true

data_list_remove:
    pattern: /{id}/remove
    defaults: { _controller: sl_core.data_list.controller:removeAction }
    requirements:
        id: \d+

data_list_delete:
    pattern: /{id}/delete
    defaults: { _controller: sl_core.data_list.controller:deleteAction }
    requirements:
        id: \d+
        _method: DELETE

data_list_update_checkbox:
    pattern: /{id}/updateCheckbox
    defaults: { _controller: sl_core.data_list.controller:updateCheckboxAction }
    requirements:
        id: \d+
        _method: PUT 