front_new:
    pattern: /{entity_class_id}/new
    defaults: { _controller: SLCoreBundle:Front:new }
    requirements:
        entity_class_id: \d+
        _method: GET 
front_create:
    pattern: /{entity_class_id}/create
    defaults: { _controller: SLCoreBundle:Front:create }
    requirements:
        entity_class_id: \d+
        _method: POST 
front_show:
    pattern: /{entity_class_id}.{entity_id}/show
    defaults: { _controller: SLCoreBundle:Front:show }
    requirements:
        entity_class_id: \d+ 
        entity_id: \d+ 
        _method: GET
front_edit:
    pattern: /{entity_class_id}.{entity_id}/edit
    defaults: { _controller: SLCoreBundle:Front:edit }
    requirements:
        entity_class_id: \d+
        entity_id: \d+
        _method: GET
front_update:
    pattern: /{entity_class_id}.{entity_id}/update
    defaults: { _controller: SLCoreBundle:Front:update }
    requirements:
        entity_class_id: \d+
        entity_id: \d+
        _method: PUT
front_remove:
    pattern: /{entity_class_id}.{entity_id}/remove
    defaults: { _controller: SLCoreBundle:Front:remove }
    requirements:
        entity_class_id: \d+
        entity_id: \d+
        _method: GET
front_delete:
    pattern: /{entity_class_id}.{entity_id}/delete
    defaults: { _controller: SLCoreBundle:Front:delete }
    requirements:
        entity_class_id: \d+
        entity_id: \d+
        _method: DELETE
front_edit_version:
    pattern: /{entity_class_id}.{entity_id}/edit_version
    defaults: { _controller: SLCoreBundle:Front:editVersion }
    requirements:
        entity_class_id: \d+
        entity_id: \d+
        _method: GET
front_update_version:
    pattern: /{entity_class_id}.{entity_id}/update_version
    defaults: { _controller: SLCoreBundle:Front:updateVersion }
    requirements:
        entity_class_id: \d+
        entity_id: \d+
        _method: PUT