front_new:
    pattern: /{id}/new
    defaults: { _controller: SLCoreBundle:Front:new }
    requirements:
        id: \d+
front_create:
    pattern: /{id}/create
    defaults: { _controller: SLCoreBundle:Front:create }
    requirements:
        id: \d+
        _method: POST 
front_show:
    pattern: /{id}.{entity_id}/show
    defaults: { _controller: SLCoreBundle:Front:show }
    requirements:
        id: \d+ 
        entity_id: \d+ 
front_edit:
    pattern: /{id}.{entity_id}/edit
    defaults: { _controller: SLCoreBundle:Front:edit }
    requirements:
        id: \d+
        entity_id: \d+
front_update:
    pattern: /{id}.{entity_id}/update
    defaults: { _controller: SLCoreBundle:Front:update }
    requirements:
        id: \d+
        entity_id: \d+
        _method: PUT
front_remove:
    pattern: /{id}.{entity_id}/remove
    defaults: { _controller: SLCoreBundle:Front:remove }
    requirements:
        id: \d+
        entity_id: \d+
front_delete:
    pattern: /{id}.{entity_id}/delete
    defaults: { _controller: SLCoreBundle:Front:delete }
    requirements:
        id: \d+
        entity_id: \d+
        _method: DELETE
front_version:
    pattern: /{id}.{entity_id}/version
    defaults: { _controller: SLCoreBundle:Front:version }
    requirements:
        id: \d+
        entity_id: \d+