front_end:
    pattern:  /front_end
    defaults: { _controller: "SLCoreBundle:Main:indexFrontEnd" }

back_end:
    pattern:  /back_end
    defaults: { _controller: "SLCoreBundle:Main:indexBackEnd" }