object:
    pattern: /
    defaults: { _controller: SLCoreBundle:ObjectCRD:index }
    requirements:
        _method: GET

object_new:
    pattern: /new/{id}
    defaults: { _controller: SLCoreBundle:ObjectCRD:new, id:0 }
    requirements:
        _method: GET 

object_create:
    pattern: /create/{id}
    defaults: { _controller: SLCoreBundle:ObjectCRD:create }
    requirements:
        _method: POST 

object_edit:
    pattern: /{id}/edit
    defaults: { _controller: SLCoreBundle:ObjectUpdate:edit }
    requirements:
        id: \d+
        _method: GET

object_update:
    pattern: /{id}/update
    defaults: { _controller: SLCoreBundle:ObjectUpdate:update }
    requirements:
        id: \d+
        _method: PUT

object_show:
    pattern: /{id}/show
    defaults: { _controller: SLCoreBundle:ObjectCRD:show }
    requirements:
        id: \d+
        _method: GET 

object_remove:
    pattern: /{id}/remove
    defaults: { _controller: SLCoreBundle:ObjectCRD:remove }
    requirements:
        id: \d+
        _method: GET 

object_delete:
    pattern: /{id}/delete
    defaults: { _controller: SLCoreBundle:ObjectCRD:delete }
    requirements:
        id: \d+
        _method: DELETE

object_update_icon:
    pattern: /{id}/updateIcon
    defaults: { _controller: SLCoreBundle:ObjectUpdate:updateIcon }
    requirements:
        id: \d+
        _method: PUT 

object_update_checkbox:
    pattern: /{id}/update_checkbox
    defaults: { _controller: SLCoreBundle:ObjectUpdate:updateCheckbox }
    requirements:
        id: \d+
        _method: PUT 

object_edit_calculated_name:
    pattern: /{id}/edit_calculated_name
    defaults: { _controller: SLCoreBundle:ObjectUpdate:editCalculatedName }
    requirements:
        id: \d+
        _method: GET 

object_update_calculated_name:
    pattern:  /{id}/update_calculated_name
    defaults: { _controller: SLCoreBundle:ObjectUpdate:updateCalculatedName }
    requirements:
        id: \d+
        _method: PUT