property_new:
    pattern: /{id}/new
    defaults: { _controller: SLCoreBundle:Property:new }
    requirements:
        id: \d+
        _method: GET

property_choice_form:
    pattern: /{id}/choice_form
    defaults: { _controller: SLCoreBundle:Property:choiceForm }
    requirements:
        id: \d+
        _method: GET

property_create:
    pattern: /{id}/create/{formMode}
    defaults: { _controller: SLCoreBundle:Property:create }
    requirements: 
        id: \d+
        _method: POST

property_edit:
    pattern: /{id}/edit
    defaults: { _controller: SLCoreBundle:Property:edit }
    requirements:
        id: \d+
        _method: GET

property_update:
    pattern: /{id}/update
    defaults: { _controller: SLCoreBundle:Property:update }
    requirements:
        id: \d+
        _method: PUT

property_remove:
    pattern: /{id}/remove
    defaults: { _controller: SLCoreBundle:Property:remove }
    requirements:
        id: \d+
        _method: GET

property_delete:
    pattern:  /{id}/delete
    defaults: { _controller: SLCoreBundle:Property:delete }
    requirements:
        id: \d+
        _method: DELETE 

property_update_checkbox:
    pattern:  /{id}/updateCheckbox
    defaults: { _controller: SLCoreBundle:Property:updateCheckbox }
    requirements:
        id: \d+
        _method: PUT