property_new:
    pattern: /{id}/new
    defaults: { _controller: SLCoreBundle:Property:new }
    requirements:
        id: \d+
        _method: GET

property_select_form:
    pattern: /{id}/select_form
    defaults: { _controller: SLCoreBundle:Property:selectForm }
    requirements:
        id: \d+
        _method: GET

property_create:
    pattern: /{id}/create/{formMode}
    defaults: { _controller: SLCoreBundle:Property:create }
    requirements: 
        id: \d+
        _method: POST

property_edit:
    pattern: /{entity_class_id}.{id}/edit
    defaults: { _controller: SLCoreBundle:Property:edit }
    requirements:
        entity_class_id: \d+
        id: \d+
        _method: GET

property_update:
    pattern: /{entity_class_id}.{id}/update
    defaults: { _controller: SLCoreBundle:Property:update }
    requirements:
        entity_class_id: \d+
        id: \d+
        _method: PUT

property_remove:
    pattern: /{entity_class_id}.{id}/remove
    defaults: { _controller: SLCoreBundle:Property:remove }
    requirements:
        entity_class_id: \d+
        id: \d+
        _method: GET

property_delete:
    pattern:  /{entity_class_id}.{id}/delete
    defaults: { _controller: SLCoreBundle:Property:delete }
    requirements:
        entity_class_id: \d+
        id: \d+
        _method: DELETE

property_update_checkbox:
    pattern:  /{id}/updateCheckbox
    defaults: { _controller: SLCoreBundle:Property:updateCheckbox }
    requirements:
        id: \d+
        _method: PUT