search:
    pattern:  /
    defaults: { _controller: SLCoreBundle:Search:search }
    options:
        expose: true

search_result:
    pattern:  /search_result/{pattern}.{objectTechnicalName}
    defaults: { _controller: SLCoreBundle:Search:refreshJsTreeSearchResults }
    options:
        expose: true
