search:
    pattern:  /
    defaults: { _controller: SLCoreBundle:Search:search }
    requirements:
        _method: POST 
    options:
        expose: true
search_result:
    pattern:  /search_result/{pattern}.{entityClassTechnicalName}
    defaults: { _controller: SLCoreBundle:Search:refreshJsTreeSearchResults } 
    requirements:
        _method: POST 
    options:
        expose: true
